---

- name: update apt repo cache and install basic linux tools
  become: yes
  apt:
    pkg:
      - vim
      - curl
      - htop
      - wget
      - net-tools
      - iptables
    update_cache: yes


  